services:
  ollama:
    image: ghcr.io/ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    profiles: [linux]

  webui:
    image: ghcr.io/open-webui/open-webui:latest
    ports:
      - "8080:8080"
    environment:
      # Because Ollama container is not available on Apple Silicon
      # So we use Ollama server on the host machine
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      # Uncomment to use Ollama server in the container
      # - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_NAME="☕️ DEV Cafe"
      # Skip the login page
      - WEBUI_AUTH=False
    volumes:
      - open-webui-data:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  open-webui-data:
  ollama-data:
