version: "3"

tasks:
  default:
    desc: "List tasks"
    cmd: task --list

  init:
    desc: "Initialize the project"
    cmds:
      - npm run prepare

  deploy:
    desc: "Deploy the project"
    prompt: "Are you sure you want to deploy?"
    dotenv:
      - .env
    cmd: |
      az deployment group create \
        --name deepseek-on-aca \
        --resource-group $AZURE_RESOURCE_GROUP \
        --parameters ./infra/main.bicepparam \
        --template-file ./infra/main.bicep

  destroy:
    desc: "Destroy the project"
    prompt: "Are you sure you want to destroy?"
    dotenv:
      - .env
    cmd: |
      az deployment group create \
        --resource-group $AZURE_RESOURCE_GROUP \
        --template-file ./infra/empty.bicep
        --mode Complete
